export { default as Contact } from "./Contact"
export { default as Main } from "./Main"
export { default as MileStone } from "./MileStone"
export { default as SkillTree } from "./SkillTree"
export { default as resume } from "./resume.json"
